spring:
  application:
    name: lovable-clone

  datasource:
    url: jdbc:mysql://localhost:3306/lovable_clone
    username: root
    password: baGGa311@

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

jwt:
  secret-key: aqswdefrgthyjukiloppolikujyhtgrfedwsqa


